travis:
  secure:
    BINSTAR_TOKEN: VSgqm7UZWxBr8RtogbGwSydLy8v2s9OLB10fpB8+QFE9VuU7N++oS+G6URm8je6lkyaBnPLNaBZXxpV4rUEfH/WBcENB825YRfaw8eZBXncDNBafzePjguAcWKpFlHjE1s0GqLUKA9wXzWM5Wus2lb2fXU5b+GiiLw6yuaI9yBG3TRw4Uce822n2oW5otStPpYN4F65rI3GtI4WzA2FAbNBlv8Me6EJAY7lpPloi0OX1NDvVJoLctZ2sE5AsAcM5pOSij43kgdtK/AP2+KGh3G4c9BeTgbjv/G9UONzvhsj5Cyu8yCQesWXUfM4etiGbNxsWFfEAQDyA/292dKTzJua4b08F49efmxfcaONGUHq5kwZLDujTTQlk4pY6DqKy7jgB24EQwAH31t4tt3YY0gWgWBLhUiE5eMO+ysWB5PWG41CoRJI3tUMztUc6QECeh5A9oy62S3LJfdBfEIADzGSM1qov4Q8bjxYSgndU43LONcul+ojn/qOnRxNC7XvkF22BWBfOgLR0ELNqB8AFrykvnfGtE8QgU2kV04nZxJuurqnaKZ7W3ntouvHLKTb1QpX1c/dkQSdJesMBSl/f6soVEwU6XxmZN9Yp4609b1P74Cv9vP1cmWQt8dMf+/UxIoSwRMRnMwiMS+3rhApDNbVc+tEnX2RZ0E5JOGdxol8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
